rendering: ~

cache_control:
  class: opCacheControlFilter

security:  ~

# insert your own filters here

cache:     ~
common:    ~
execution:
  class: sfOpenPNEExecutionFilter
  param:
    type: execution
